"""created ratings table and added more columns to rating staging table

Revision ID: 01e281cb0a13
Revises: 288c9c2dc667
Create Date: 2026-08-17 12:50:47.507673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e281cb0a13'
down_revision: Union[str, Sequence[str], None] = '288c9c2dc667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('source_staging_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('order_entry_id', sa.String(length=50), nullable=True),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.Column('verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('source_channel', sa.String(length=20), nullable=True),
    sa.Column('review_classification', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ai_moderation_score', sa.Float(), nullable=True),
    sa.Column('ai_validation_flags', sa.String(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('blocked_by', sa.String(length=100), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.add_column('rating_staging', sa.Column('moderated_by', sa.String(length=100), nullable=True))
    op.add_column('rating_staging', sa.Column('moderated_at', sa.DateTime(), nullable=True))
    op.add_column('rating_staging', sa.Column('published_rating_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_staging', 'published_rating_id')
    op.drop_column('rating_staging', 'moderated_at')
    op.drop_column('rating_staging', 'moderated_by')
    op.drop_table('ratings')
    # ### end Alembic commands ###
