"""added ai_columns to the rating_staging table

Revision ID: 288c9c2dc667
Revises: 
Create Date: 2026-08-17 11:53:50.538819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288c9c2dc667'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_staging', sa.Column('ai_validation_status', sa.String(length=20), nullable=True))
    op.add_column('rating_staging', sa.Column('ai_validation_score', sa.Float(), nullable=True))
    op.add_column('rating_staging', sa.Column('ai_validation_flags', sa.Text(), nullable=True))
    op.add_column('rating_staging', sa.Column('ai_triggered_by', sa.String(length=100), nullable=True))
    op.add_column('rating_staging', sa.Column('ai_triggered_at', sa.DateTime(), nullable=True))
    op.add_column('rating_staging', sa.Column('requires_manual_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_staging', 'requires_manual_review')
    op.drop_column('rating_staging', 'ai_triggered_at')
    op.drop_column('rating_staging', 'ai_triggered_by')
    op.drop_column('rating_staging', 'ai_validation_flags')
    op.drop_column('rating_staging', 'ai_validation_score')
    op.drop_column('rating_staging', 'ai_validation_status')
    # ### end Alembic commands ###
